<form action = "admin_member.php" name="loginform" method = "post" >
<center><h3 style = "color: white">You must be authorised to be here!</center></h3>

<table align="center" width ="300" border ="2">
<tr>
<td width ="50%" align ="right"><b>Username: </b></td>
<td><input type="text" name="username" size="30" maxlength="10"  /></td>
</tr>
<tr>
<td width ="50%" align ="right"><b>Password: </b></td>
<td><input type="password" name="passwd" size="30" maxlength="30"  /></td>
</tr>
<tr><td colspan = "2"><center><input type="submit" name="login" value="Login" /></center></td>
</tr>
</table>
<br />
<center>